default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  user: postgres
  password:

development:
  <<: *default
  database: twistedchat_development

test:
  <<: *default
  database: twistedchat_test

production:
  adapter: postgresql
  pool: 15
  timeout: 5000
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
